load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "bitset",
    hdrs = ["bitset.h"],
)

cc_library(
    name = "unique_counter",
    hdrs = ["unique_counter.h"],
)
