load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "poly_int_test",
    srcs = ["poly_int_test.cpp"],
    deps = [
        "//math/poly:poly_int",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
