load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "unique_merge_test",
    srcs = ["unique_merge_test.cpp"],
    deps = [
        "//misc:unique_merge",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
