#ifdef BASE_MO_HILBERT_ALL
#define BASE_MO_HILBERT_CLEAR
#define BASE_MO_HILBERT_HANDLE
#define BASE_MO_HILBERT_RESERVE
#define _BASE_MO_HILBERT_HANDLE
#endif

#ifdef BASE_MO_HILBERT_HANDLE
#define _BASE_MO_HILBERT_HANDLE
#endif
