load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "forward_star_stack_test",
    srcs = ["forward_star_stack_test.cpp"],
    deps = [
        "//collections/forward_star:forward_star_stack",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
