load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stair_container_macros",
    hdrs = ["stair_container_macros.h"],
)

cc_library(
    name = "stair_container",
    hdrs = ["stair_container.h"],
)
