load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "forward_star_test",
    srcs = ["forward_star_test.cpp"],
    deps = [
        "//graphs/forward_star",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
