load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "unweighted_forward_star_test",
    srcs = ["unweighted_forward_star_test.cpp"],
    deps = [
        "//graphs/forward_star:unweighted_forward_star",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
