#ifdef BASE_FENWICK_ALL
#define BASE_FENWICK_CALC_PREFIX_RETURN
#define BASE_FENWICK_CALC_RANGE
#define BASE_FENWICK_RESERVE
#endif

#ifdef BASE_FENWICK_CALC_RANGE
#define BASE_FENWICK_CALC_PREFIX_RETURN
#endif
