#ifdef MANACHER_ALL
#define MANACHER_CALC_CHAR_ARRAY
#define MANACHER_CALC_STRING
#define MANACHER_EVEN_LOWER
#define MANACHER_EVEN_SIZE
#define MANACHER_EVEN_UPPER
#define MANACHER_LONGEST_PALINDROME
#define MANACHER_ODD_LOWER
#define MANACHER_ODD_SIZE
#define MANACHER_ODD_UPPER
#define MANACHER_RESERVE
#endif
