#ifdef BASE_SPARSE_TABLE_ALL
#define BASE_SPARSE_TABLE_CALC
#define BASE_SPARSE_TABLE_RESERVE
#define _BASE_SPARSE_TABLE_CALC
#endif

#ifdef BASE_SPARSE_TABLE_CALC
#define _BASE_SPARSE_TABLE_CALC
#endif
