load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "complex_test",
    srcs = ["complex_test.cpp"],
    deps = [
        "//math/complex",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
