load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ctz",
    hdrs = ["ctz.h"],
)

cc_library(
    name = "ctz128",
    hdrs = ["ctz128.h"],
)

cc_library(
    name = "gray_code",
    hdrs = ["gray_code.h"],
)

cc_library(
    name = "inv_gray_code",
    hdrs = ["inv_gray_code.h"],
)

cc_library(
    name = "next_pow2_32",
    hdrs = ["next_pow2_32.h"],
)

cc_library(
    name = "submasks",
    hdrs = ["submasks.h"],
)
