#ifdef COMPLEX_ALL
#define COMPLEX_ADD_INLINE
#define COMPLEX_CONJ
#define COMPLEX_DIV_INLINE_DOUBLE
#define COMPLEX_INIT
#define COMPLEX_INIT_CONJ
#define COMPLEX_INIT_MUL
#define COMPLEX_INIT_POLAR
#define COMPLEX_INIT_SUB
#define COMPLEX_MUL
#define COMPLEX_MUL_INLINE
#define COMPLEX_SUB
#endif

#ifdef COMPLEX_MUL
#define COMPLEX_INIT_MUL
#endif

#ifdef COMPLEX_SUB
#define COMPLEX_INIT_SUB
#endif
