load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "min_prime_tagger",
    hdrs = ["min_prime_tagger.h"],
)

cc_library(
    name = "prime_checker_quick",
    hdrs = ["prime_checker_quick.h"],
)

cc_library(
    name = "prime_checker_slow",
    hdrs = ["prime_checker_slow.h"],
)

cc_library(
    name = "prime_checker",
    hdrs = ["prime_checker.h"],
)

cc_library(
    name = "prime_gen",
    hdrs = ["prime_gen.h"],
)
