load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "add_inline_test",
    srcs = ["add_inline_test.cpp"],
    deps = [
        "//math/mod_operators:add_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "add_test",
    srcs = ["add_test.cpp"],
    deps = [
        "//math/mod_operators:add",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "exp_test",
    srcs = ["exp_test.cpp"],
    deps = [
        "//math/mod_operators:exp",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "fix_inline_test",
    srcs = ["fix_inline_test.cpp"],
    deps = [
        "//math/mod_operators:fix_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "fix_test",
    srcs = ["fix_test.cpp"],
    deps = [
        "//math/mod_operators:fix",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "inv_test",
    srcs = ["inv_test.cpp"],
    deps = [
        "//math/mod_operators:inv",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mod_exp_utils_test",
    srcs = ["mod_exp_utils_test.cpp"],
    deps = [
        "//math/mod_operators:mod_exp_utils",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_inline_test",
    srcs = ["mul_inline_test.cpp"],
    deps = [
        "//math/mod_operators:mul_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_test",
    srcs = ["mul_test.cpp"],
    deps = [
        "//math/mod_operators:mul",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "slight_fix_inline_test",
    srcs = ["slight_fix_inline_test.cpp"],
    deps = [
        "//math/mod_operators:slight_fix_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "sub_test",
    srcs = ["sub_test.cpp"],
    deps = [
        "//math/mod_operators:sub",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
