load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "disjoint_set_size_groups_macros",
    hdrs = ["disjoint_set_size_groups_macros.h"],
)

cc_library(
    name = "disjoint_set_size_groups",
    hdrs = ["disjoint_set_size_groups.h"],
)

cc_library(
    name = "disjoint_set_size_macros",
    hdrs = ["disjoint_set_size_macros.h"],
)

cc_library(
    name = "disjoint_set_size_parity_macros",
    hdrs = ["disjoint_set_size_parity_macros.h"],
)

cc_library(
    name = "disjoint_set_size_parity",
    hdrs = ["disjoint_set_size_parity.h"],
)

cc_library(
    name = "disjoint_set_size",
    hdrs = ["disjoint_set_size.h"],
)
