#ifdef FFT_UTILS_ALL
#define FFT_UTILS_MUL_BIGINT
#define FFT_UTILS_MUL_COMPLEX_VECTOR
#endif

#ifdef FFT_UTILS_MUL_BIGINT
#define BIGINT_ASSIGN_COMPLEX_VECTOR
#define BIGINT_OUTPUT_COMPLEX_VECTOR

#define FFT_UTILS_MUL_COMPLEX_VECTOR

#define _FFT_UTILS_COMPLEX_VECTOR_3
#endif
