#ifdef FFT_MUL_UTILS_ALL
#define FFT_MUL_UTILS_MUL_INLINE_MODIFY_2D
#define FFT_MUL_UTILS_MUL_INLINE_REAL
#define FFT_MUL_UTILS_MUL_REAL
#endif

#ifdef FFT_MUL_UTILS_MUL_INLINE_MODIFY_2D
#define COMPLEX_MUL_INLINE
#define FFT_UTILS_FFT_2D
#endif

#ifdef FFT_MUL_UTILS_MUL_INLINE_REAL
#define COMPLEX_DIV_INLINE_DOUBLE
#define COMPLEX_INIT
#define COMPLEX_INIT_CONJ
#define COMPLEX_MUL_INLINE
#define FFT_MUL_UTILS_MUL_REAL
#define _FFT_UTILS_SHRINK_COMPLEX_VECTOR
#endif

#ifdef FFT_MUL_UTILS_MUL_REAL
#define COMPLEX_DIV_INLINE_DOUBLE
#define COMPLEX_INIT
#define COMPLEX_INIT_CONJ
#define COMPLEX_MUL_INLINE
#define _FFT_UTILS_SHRINK_COMPLEX_VECTOR
#endif

#include "math/complex/complex_macros.h"
#include "math/fft/fft_utils_macros.h"
