#ifdef NTT_UTILS_FIX_ALL
#define NTT_UTILS_FIX_MUL_INLINE_MODIFY
#define NTT_UTILS_FIX_RECURRENCE_INLINE
#endif

#ifdef NTT_UTILS_FIX_RECURRENCE_INLINE
#define NTT_UTILS_FIX_MUL_INLINE_MODIFY
#define MOD_INT_ADD_INLINE
#endif

#define MOD_INT_EXP
#define MOD_INT_INV
#define MOD_INT_MUL_INLINE

#include "math/mod/mod_int_macros.h"
