#ifdef BIGINT_ALL
#define BIGINT_ADD
#define BIGINT_ADD_INLINE
#define BIGINT_ADD_INLINE_INT
#define BIGINT_ADD_INT
#define BIGINT_ASSIGN
#define BIGINT_ASSIGN_CHAR_ARRAY
#define BIGINT_ASSIGN_COMPLEX_VECTOR
#define BIGINT_ASSIGN_INT
#define BIGINT_ASSIGN_STRING
#define BIGINT_CMP
#define BIGINT_CMP_INT
#define BIGINT_CONSTRUCT_EMPTY
#define BIGINT_CONSTRUCT_INT
#define BIGINT_DIGIT_COUNT
#define BIGINT_DIGIT_SUM
#define BIGINT_DIV_INLINE
#define BIGINT_DIV_INLINE_INT
#define BIGINT_DIV_MOD_INLINE_INT
#define BIGINT_EQ_INT
#define BIGINT_GCD_INLINE
#define BIGINT_GE
#define BIGINT_GE_INT
#define BIGINT_GT_INT
#define BIGINT_INIT_ADD
#define BIGINT_INIT_CAPACITY
#define BIGINT_INIT_CHAR_ARRAY
#define BIGINT_INIT_INT
#define BIGINT_INIT_MUL
#define BIGINT_LT
#define BIGINT_LT_INT
#define BIGINT_MOD_DIV_INLINE
#define BIGINT_MOD_INLINE
#define BIGINT_MOD_INT
#define BIGINT_MUL
#define BIGINT_MUL_INLINE
#define BIGINT_MUL_INLINE_INT
#define BIGINT_MUL_INT
#define BIGINT_NE_INT
#define BIGINT_OUTPUT
#define BIGINT_OUTPUT_CHAR_ARRAY
#define BIGINT_OUTPUT_COMPLEX_VECTOR
#define BIGINT_OUTPUT_FAST
#define BIGINT_SHRINK
#define BIGINT_SUB
#define BIGINT_SUB_INLINE
#define BIGINT_SUB_INLINE_INT
#endif

#ifdef BIGINT_ADD
#define BIGINT_ADD_INLINE
#define BIGINT_INIT_ADD
#define _BIGINT_POW10
#endif

#ifdef BIGINT_ADD_INLINE
#define _BIGINT_POW10
#endif

#ifdef BIGINT_ADD_INLINE_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_ADD_INT
#define BIGINT_ADD_INLINE_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_ASSIGN_COMPLEX_VECTOR
#define BIGINT_SHRINK
#define _BIGINT_FFT_T
#define _BIGINT_POW10
#endif

#ifdef BIGINT_ASSIGN_INT
#define BIGINT_INIT_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_CMP_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_CONSTRUCT_INT
#define BIGINT_INIT_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_DIGIT_COUNT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_DIV_INLINE_INT
#define BIGINT_DIV_MOD_INLINE_INT
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_DIV_MOD_INLINE_INT
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_EQ_INT
#define BIGINT_CMP_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_GCD_INLINE
#define BIGINT_CMP
#define BIGINT_CMP_INT
#define BIGINT_MOD_DIV_INLINE
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_GE
#define BIGINT_CMP
#endif

#ifdef BIGINT_INIT_ADD
#define BIGINT_ADD_INLINE
#define _BIGINT_POW10
#endif

#ifdef BIGINT_INIT_CHAR_ARRAY
#define BIGINT_SHRINK
#endif

#ifdef BIGINT_INIT_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_INIT_MUL
#define BIGINT_ASSIGN_COMPLEX_VECTOR
#define BIGINT_SHRINK
#define FFT_MUL_UTILS_MUL_REAL
#define _BIGINT_FFT_MUL_UTILS
#define _BIGINT_FFT_T
#define _BIGINT_POW10
#endif

#ifdef BIGINT_LT
#define BIGINT_CMP
#endif

#ifdef BIGINT_LT_INT
#define BIGINT_CMP_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_MOD_DIV_INLINE
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_MOD_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_MUL_INLINE
#define BIGINT_ASSIGN_COMPLEX_VECTOR
#define BIGINT_INIT_MUL
#define BIGINT_SHRINK
#define FFT_MUL_UTILS_MUL_REAL
#define _BIGINT_FFT_MUL_UTILS
#define _BIGINT_FFT_T
#define _BIGINT_POW10
#endif

#ifdef BIGINT_MUL_INLINE_INT
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_MUL_INT
#define BIGINT_MUL_INLINE_INT
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_NE_INT
#define BIGINT_CMP_INT
#define _BIGINT_POW10
#endif

#ifdef BIGINT_OUTPUT_COMPLEX_VECTOR
#define _BIGINT_FFT_T
#endif

#ifdef BIGINT_SUB_INLINE
#define BIGINT_SHRINK
#define _BIGINT_POW10
#endif

#ifdef BIGINT_SUB_INLINE_INT
#define _BIGINT_POW10
#endif

#ifdef _BIGINT_FFT_MUL_UTILS
#include "math/fft/fft_mul_utils_macros.h"
#endif
