load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "accumulator_test",
    srcs = ["accumulator_test.cpp"],
    deps = [
        "//math/mod:accumulator",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "add_test",
    srcs = ["add_test.cpp"],
    deps = [
        "//math/mod:add",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "exp_safe_test",
    srcs = ["exp_safe_test.cpp"],
    deps = [
        "//math/mod:exp_safe",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "exp_test",
    srcs = ["exp_test.cpp"],
    deps = [
        "//math/mod:exp",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "exp128_test",
    srcs = ["exp128_test.cpp"],
    deps = [
        "//math/mod:exp128",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "fix_inline_test",
    srcs = ["fix_inline_test.cpp"],
    deps = [
        "//math/mod:fix_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "fix_test",
    srcs = ["fix_test.cpp"],
    deps = [
        "//math/mod:fix",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "inv_all_test",
    srcs = ["inv_all_test.cpp"],
    deps = [
        "//math/mod:inv_all",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "inv_test",
    srcs = ["inv_test.cpp"],
    deps = [
        "//math/mod:inv",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "log_coprime_test",
    srcs = ["log_coprime_test.cpp"],
    deps = [
        "//math/mod:log_coprime",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "log_test",
    srcs = ["log_test.cpp"],
    deps = [
        "//math/mod:log",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mod_exp_utils_test",
    srcs = ["mod_exp_utils_test.cpp"],
    deps = [
        "//math/mod:mod_exp_utils",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_inline_test",
    srcs = ["mul_inline_test.cpp"],
    deps = [
        "//math/mod:mul_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_inline_safe_test",
    srcs = ["mul_inline_safe_test.cpp"],
    deps = [
        "//math/mod:mul_inline_safe",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_safe_test",
    srcs = ["mul_safe_test.cpp"],
    deps = [
        "//math/mod:mul_safe",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "mul_test",
    srcs = ["mul_test.cpp"],
    deps = [
        "//math/mod:mul",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "power_tower_test",
    srcs = ["power_tower_test.cpp"],
    deps = [
        "//math/mod:power_tower",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "primitive_root_prime_use_primes_test",
    srcs = ["primitive_root_prime_use_primes_test.cpp"],
    deps = [
        "//math/mod:primitive_root_prime_use_primes",
        "//math/prime:prime_generator",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "primitive_root_use_primes_test",
    srcs = ["primitive_root_use_primes_test.cpp"],
    deps = [
        "//math/mod:primitive_root_use_primes",
        "//math/prime:prime_generator",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "root_test",
    srcs = ["root_test.cpp"],
    deps = [
        "//math/mod:primitive_root_use_primes",
        "//math/mod:root",
        "//math/prime:prime_generator",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "slight_fix_inline_test",
    srcs = ["slight_fix_inline_test.cpp"],
    deps = [
        "//math/mod:slight_fix_inline",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "slight_fix_test",
    srcs = ["slight_fix_test.cpp"],
    deps = [
        "//math/mod:slight_fix",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "sub_test",
    srcs = ["sub_test.cpp"],
    deps = [
        "//math/mod:sub",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
