load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "bitset_test",
    srcs = ["bitset_test.cpp"],
    deps = [
        "//collections:bitset",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
