load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "bitset_test",
    srcs = ["bitset_test.cpp"],
    deps = [
        "//collections:bitset",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "disjoint_set_test",
    srcs = ["disjoint_set_test.cpp"],
    deps = [
        "//collections:disjoint_set",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "hashmap_test",
    srcs = ["hashmap_test.cpp"],
    deps = [
        "//collections:hashmap",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "hashset_test",
    srcs = ["hashset_test.cpp"],
    deps = [
        "//collections:hashset",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "unique_counter_test",
    srcs = ["unique_counter_test.cpp"],
    deps = [
        "//collections:unique_counter",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "vector2d_test",
    srcs = ["vector2d_test.cpp"],
    deps = [
        "//collections:vector2d",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
