load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "hilbert_order_test",
    srcs = ["hilbert_order_test.cpp"],
    deps = [
        "//math/fractal:hilbert_order",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
