load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "hilbert_order",
    hdrs = ["hilbert_order.h"],
    deps = ["//common:macros"],
)
