load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "lazy_treap_reverse_test",
    srcs = ["lazy_treap_reverse_test.cpp"],
    deps = [
        "//ds/treap:base_lazy_treap_macros",
        "//ds/treap:lazy_treap_reverse",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "treap_forest_set_test",
    srcs = ["treap_forest_set_test.cpp"],
    deps = [
        "//ds/treap:base_treap_forest_macros",
        "//ds/treap:treap_forest_set",
        "//ds/treap:treap_forest_set_macros",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "treap_multiset_test",
    srcs = ["treap_multiset_test.cpp"],
    deps = [
        "//ds/treap:base_treap_macros",
        "//ds/treap:treap_multiset",
        "//ds/treap:treap_multiset_macros",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "treap_set_test",
    srcs = ["treap_set_test.cpp"],
    deps = [
        "//ds/treap:base_treap_macros",
        "//ds/treap:treap_set",
        "//ds/treap:treap_set_macros",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "treap_sum_test",
    srcs = ["treap_sum_test.cpp"],
    deps = [
        "//ds/treap:base_treap_macros",
        "//ds/treap:treap_sum",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
