#ifdef BASE_TREAP_ALL
#define BASE_TREAP_CALC_PREFIX
#define BASE_TREAP_CALC_PREFIX_RETURN
#define BASE_TREAP_RESERVE
#define BASE_TREAP_UPDATE
#endif

#ifdef BASE_TREAP_CALC_PREFIX_RETURN
#define BASE_TREAP_CALC_PREFIX
#endif
