#ifdef BASE_TREAP_FOREST_ALL
#define BASE_TREAP_FOREST_CALC_PREFIX
#define BASE_TREAP_FOREST_CALC_RANGE
#define BASE_TREAP_FOREST_CALC_SUFFIX
#define BASE_TREAP_FOREST_ERASE
#define BASE_TREAP_FOREST_INIT_ORDERED_ITEMS
#define BASE_TREAP_FOREST_RESERVE_ROOTS
#define BASE_TREAP_FOREST_UPDATE
#endif

#ifdef BASE_TREAP_FOREST_CALC_PREFIX
#define _BASE_TREAP_CALC_PREFIX
#endif

#ifdef BASE_TREAP_FOREST_CALC_RANGE
#define _BASE_TREAP_CALC_RANGE
#endif

#ifdef BASE_TREAP_FOREST_CALC_SUFFIX
#define _BASE_TREAP_CALC_SUFFIX
#endif

#ifdef BASE_TREAP_FOREST_ERASE
#define _BASE_TREAP_ERASE
#endif

#ifdef BASE_TREAP_FOREST_INIT_ITEMS
#define _BASE_TREAP_INIT_ORDERED_ITEMS
#endif

#ifdef BASE_TREAP_FOREST_UPDATE
#define _BASE_TREAP_UPDATE
#endif

#include "ds/treap/base_treap_macros.h"
